version: '3'

services:
  api:
    container_name: "post-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    container_name: posts_postgres_db
    image: postgres:12
    ports:
          - 5431:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
